export * from './types';
export * from './registry';
export { createCursorAdapter } from './cursor';
export { createClaudeCodeAdapter } from './claudeCode';
export { createCopilotAdapter } from './copilot';
export { createCodeiumAdapter } from './codeium';
export { createAiderAdapter } from './aider';
export { createContinueAdapter } from './continue';
export { createCodyAdapter } from './cody';
export { createAmazonQAdapter } from './amazonQ';
export { createGeminiCliAdapter } from './geminiCli';
export { createCodexCliAdapter } from './codex';
export { createLegacyHeuristicAdapter } from './legacy';
